name: "Unit tests"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l -e -o pipefail {0}

    strategy:
      matrix:
        go: [ "1.16" ]
#        irods: [ "4.2.7", "4.2.8" ]

    services:
      irods:
        image: wsinpg/ub-16.04-irods-4.2.7:latest
        ports:
          - 1247:1247

    env:
      WSI_CONDA_CHANNEL: "https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic"
      CONDA_TEST_ENVIRONMENT: "testenv"
      IRODS_VERSION: "4.2.7"
      BATON_VERSION: "2.0.1"

    steps:
    - uses: actions/checkout@v2

    - name: "Set up Go ${{ matrix.go }}"
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: "Initialize Miniconda"
      run: |
        echo 'source $CONDA/etc/profile.d/conda.sh' >> "$HOME/.bash_profile"
        conda init -v bash

    - name: "Configure Miniconda"
      run: |
        conda config --set auto_update_conda False
        conda config --prepend channels "$WSI_CONDA_CHANNEL"
        conda config --append channels conda-forge
        conda info

    - name: "Install iRODS clients"
      run: |
        conda create -y -n "$CONDA_TEST_ENVIRONMENT"
        conda install -y -n "$CONDA_TEST_ENVIRONMENT" "irods-icommands ==$IRODS_VERSION"
        conda install -y -n "$CONDA_TEST_ENVIRONMENT" "baton >$BATON_VERSION"

    - name: "Configure iRODS clients"
      run: |
        conda activate "$CONDA_TEST_ENVIRONMENT"

        mkdir -p "$HOME/.irods"
        cat <<'EOF' > "$HOME/.irods/irods_environment.json"
        {
            "irods_host": "localhost",
            "irods_port": 1247,
            "irods_user_name": "irods",
            "irods_zone_name": "testZone",
            "irods_home": "/testZone/home/irods",
            "irods_default_resource": "testResc"
        }
        EOF
        echo "irods" | script -q -c "iinit" /dev/null

        ienv
        ils

        baton-do --version

    - name: "Install test runner"
      run: |
        go get github.com/onsi/ginkgo/ginkgo
        go get github.com/onsi/gomega/...

    - name: "Run tests"
      run: |
        conda activate "$CONDA_TEST_ENVIRONMENT"
        make test
